Neos:
  Fusion:
    defaultContext:
      Instagram: 'CodeQ\Instagram\Eel\Instagram'
  Neos:
    fusion:
      autoInclude:
        CodeQ.Instagram: true
CodeQ:
  Instagram:
    accessToken: 'accessToken'
