Neos:
  Fusion:
    defaultContext:
      Instagram: 'CodeQ\Instagram\Eel\Instagram'
  Neos:
    fusion:
      autoInclude:
        CodeQ.Instagram: true
  Flow:
    mvc:
      routes:
        'CodeQ.Instagram':
          position: 'start'
